description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: 25 November 2021
fullnameofperson: Alex Williams
selfIdentification: Coordinator, Researcher Services, Griffith University Library
colour1: "#c5c3c6"  # sidebar background 
colour2: "#46494c"  # colour of name and desc
colour3: "#3da35d"  # colour of Menu links
colour4: "#96e072" # trying to be background colour - still experimenting 
colour5: "#e8fccf" # menu link colour when hover
