description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: 25 November 2021
fullnameofperson: Alex Williams
selfIdentification: Coordinator, Researcher Services, Griffith University Library
colour1: "#dcdcdd"  # sidebar background 
colour2: "#46494c"  # colour of name and desc
colour3: "#00043a"  # colour of Menu links
colour4: "#033270" # trying to be background colour - still experimenting 
colour5: "#e8fccf" # menu link colour when hover
